# Site settings
title: 高雄市路竹區大社國民小學1965級愛信義班畢業同學會
footer: 高雄市路竹區大社國民小學1965級愛信義班畢業同學會
email: dashe1965.luzhu@gmail.com
description:
lang: zh-TW

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://dashe1965.github.io # the base hostname & protocol for your site
git_address: https://github.com/dashe1965/dashe1965.github.io
git_edit_address: https://github.com/dashe1965/dashe1965.github.io/blob/main

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Asia/Taipei
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: news

- scope:
    path: _docs
    type: docs
  values:
    layout: docs_no_nav
    sectionid: docs

- scope:
    path: _docs/origin
    type: docs
  values:
    layout: docs_no_nav
    sectionid: origin

- scope:
    path: _docs/about
    type: docs
  values:
    layout: docs_no_nav
    sectionid: about

- scope:
    path: _docs/ai_classmates
    type: docs
  values:
    layout: docs_no_nav
    sectionid: ai_classmates

- scope:
    path: _docs/xin_classmates
    type: docs
  values:
    layout: docs_no_nav
    sectionid: xin_classmates

- scope:
    path: _docs/yi_classmates
    type: docs
  values:
    layout: docs_no_nav
    sectionid: yi_classmates

- scope:
    path: _docs/honors
    type: docs
  values:
    layout: docs_no_nav
    sectionid: honors

- scope:
    path: _docs/life
    type: docs
  values:
    layout: docs_no_nav
    sectionid: life

- scope:
    path: _docs/donate
    type: docs
  values:
    layout: docs_no_nav
    sectionid: donate

- scope:
    path: _docs/update
    type: docs
  values:
    layout: docs_no_nav
    sectionid: update

- scope:
    path: _docs/activity
    type: docs
  values:
    layout: docs_no_nav
    sectionid: activity

- scope:
    path: _docs/contact
    type: docs
  values:
    layout: docs_no_nav
    sectionid: contact

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /news/:year/:month/:day/:title/
    output: true
